apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30036 # You can specify a port in the range 30000-32767 or let Kubernetes assign one
  type: NodePort